/* Technical offers: private draft and explicitly allowlisted client document. */
(()=>{
const el=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), eur=n=>new Intl.NumberFormat('el-GR',{style:'currency',currency:'EUR'}).format(n);
const keys=['title','client','clientVat','apartment','address','date','quoteNo','validity','duration','payment','scope','notes','exclusions','internal','vat'];
let draft,edit=-1;
const fresh=()=>({type:'technical',title:'',date:new Date().toLocaleDateString('en-CA'),validity:'30 ημέρες',vat:24,stages:[]});
const stage=()=>({name:'',description:'',pricingMode:'flat',qty:1,unit:'m²',price:0,laborCost:0,materialCost:0,otherCost:0});
const quantity=r=>r.pricingMode==='flat'?1:num(r.qty);
const num=x=>Math.max(0,Number(x)||0), round=n=>Math.round((n+Number.EPSILON)*100)/100;
function calc(d){const net=round(d.stages.reduce((a,r)=>a+round(quantity(r)*num(r.price)),0)),cost=round(d.stages.reduce((a,r)=>a+round(quantity(r)*(num(r.laborCost)+num(r.materialCost)+num(r.otherCost))),0)),vat=round(net*num(d.vat)/100);return{net,cost,vat,total:round(net+vat),profit:round(net-cost),margin:net?(net-cost)/net*100:0}}
function sync(){keys.forEach(k=>draft[k]=el('tech_'+k).value);draft.vat=Math.min(100,num(draft.vat));return draft}
function summary(){sync();const t=calc(draft);el('techSummary').innerHTML=[['Καθαρή αξία πώλησης',eur(t.net)],['Εσωτερικό κόστος',eur(t.cost)],['Εκτιμώμενο κέρδος',eur(t.profit)],['Περιθώριο επί πώλησης',t.margin.toFixed(1)+'%'],['ΦΠΑ',eur(t.vat)],['Σύνολο πελάτη',eur(t.total)]].map(([a,b])=>`<div class="sumrow"><span>${a}</span><b>${b}</b></div>`).join('')}
function render(){keys.forEach(k=>el('tech_'+k).value=draft[k]??'');el('techStages').innerHTML=draft.stages.map((r,i)=>`<div class="item"><h3>Στάδιο ${i+1}</h3><label>Τρόπος χρέωσης</label><select data-i="${i}" data-k="pricingMode"><option value="flat" ${r.pricingMode==='flat'?'selected':''}>Συνολική τιμή — χωρίς ποσότητα</option><option value="unit" ${r.pricingMode!=='flat'?'selected':''}>Ποσότητα × τιμή μονάδας</option></select><label>Περιγραφή εργασίας</label><input data-i="${i}" data-k="name" value="${esc(r.name)}"><label>Αναλυτική τεχνική περιγραφή — εμφανίζεται στον πελάτη</label><textarea rows="3" data-i="${i}" data-k="description">${esc(r.description)}</textarea><div class="row3">${[['qty','Ποσότητα'],['unit','Μονάδα (m² / τ.μ. / τεμ. / κατ’ αποκοπή)'],['price','Τιμή πώλησης € / μονάδα'],['laborCost','Κόστος εργασίας € / μονάδα'],['materialCost','Κόστος υλικών € / μονάδα'],['otherCost','Λοιπά κόστη € / μονάδα']].filter(([k])=>r.pricingMode!=='flat'||!['qty','unit'].includes(k)).map(([k,l])=>`<div class="field"><label>${r.pricingMode==='flat'?l.replace(' / μονάδα','').replace('Τιμή πώλησης','Συνολική τιμή πώλησης'):l}</label><input data-i="${i}" data-k="${k}" ${k==='unit'?'':'type="number" min="0" step="0.01"'} value="${esc(r[k])}"></div>`).join('')}</div><div class="actions"><button data-move="-1" data-i="${i}" class="ghost">↑</button><button data-move="1" data-i="${i}" class="ghost">↓</button><button class="danger" data-delete="${i}">Διαγραφή σταδίου</button></div></div>`).join('');summary()}
function mode(technical){['quote','technical','history','prices','printArea','techClient'].forEach(id=>el(id).classList.toggle('hidden',id!==(technical?'technical':'quote')));el('offerType').value=technical?'technical':'standard';el('offerTypeBar').classList.remove('hidden')}
el('offerType').onchange=()=>mode(el('offerType').value==='technical');
el('techStages').oninput=e=>{const {i,k}=e.target.dataset;if(k){draft.stages[+i][k]=['name','unit','description','pricingMode'].includes(k)?e.target.value:num(e.target.value);if(k==='pricingMode'){sync();render()}else summary()}};
el('techStages').onclick=e=>{const b=e.target.closest('button');if(!b)return;sync();if(b.dataset.delete!==undefined)draft.stages.splice(+b.dataset.delete,1);else{const i=+b.dataset.i,j=i+Number(b.dataset.move);if(j>=0&&j<draft.stages.length)[draft.stages[i],draft.stages[j]]=[draft.stages[j],draft.stages[i]]}render()};
keys.forEach(k=>el('tech_'+k).oninput=summary);
el('techAdd').onclick=()=>{sync();draft.stages.push(stage());render()};
el('techNew').onclick=()=>{if(confirm('Νέα κενή τεχνική προσφορά; Αποθήκευσε πρώτα τυχόν αλλαγές.')){draft=fresh();edit=-1;render()}};
const baseHistory=renderHistory;renderHistory=function(){baseHistory();el('historyList').querySelectorAll('.item').forEach((row,i)=>{if(quotes[i]?.type==='technical')row.querySelector('.muted').textContent=(quotes[i].title||'Τεχνική προσφορά')+' · '+quotes[i].date+' · '+quotes[i].stages.length+' στάδια'})};
const baseOpen=window.openSavedQuote,basePrint=window.printSavedQuote;
function load(i){edit=i;draft=structuredClone(quotes[i]);render();mode(true)}
window.openSavedQuote=i=>{if(quotes[i]?.type==='technical')load(i);else{mode(false);baseOpen(i)}};
window.printSavedQuote=i=>{if(quotes[i]?.type==='technical'){load(i);preview()}else{mode(false);basePrint(i)}};
document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{el('technical').classList.add('hidden');el('techClient').classList.add('hidden');el('offerTypeBar').classList.toggle('hidden',b.dataset.tab!=='quote');if(b.dataset.tab==='quote')mode(el('offerType').value==='technical')}));
function valid(){sync();if(!draft.stages.length||draft.stages.some(r=>!r.name.trim()||(r.pricingMode!=='flat'&&num(r.qty)<=0))){alert('Πρόσθεσε στάδια με περιγραφή και θετική ποσότητα.');return false}return true}
// Client payload contains no internal notes, costs, margin or profit.
function clientData(){sync();const t=calc(draft);return{type:'technical',id:draft.id,title:draft.title,client:draft.client,clientVat:draft.clientVat,apartment:draft.apartment,address:draft.address,date:draft.date,quoteNo:draft.quoteNo,validity:draft.validity,delivery:draft.duration,payment:draft.payment,scope:draft.scope,notes:draft.notes,exclusions:draft.exclusions,net:t.net,vat:t.vat,total:t.total,labor:t.net,mats:0,lines:draft.stages.map(r=>({name:r.name,qty:quantity(r),unit:r.pricingMode==='flat'?'':r.unit,pricingMode:r.pricingMode,base:num(r.price),mult:1,labor:round(quantity(r)*num(r.price)),materials:0,note:r.description}))}}
el('techSave').onclick=()=>{if(!valid())return;const saved=structuredClone(draft);saved.id=draft.id||Date.now();Object.assign(saved,calc(saved));saved.lines=clientData().lines;const next=quotes.slice();const index=next.findIndex(q=>q.type==='technical'&&q.id===saved.id);if(index>=0)next[index]=saved;else next.unshift(saved);try{localStorage.setItem('apm5_quotes',JSON.stringify(next));quotes=next;draft=saved;edit=quotes.findIndex(q=>q.id===saved.id);renderHistory();if(window.airbnbContext){const c=window.airbnbContext;localStorage.setItem(c.source==='longterm'?'mgv_longterm_quote_transfer':'mgv_airbnb_quote_transfer',JSON.stringify({taskId:c.taskId||'',apartmentId:c.apartmentId,quote:clientData()}));alert('Αποθηκεύτηκε και συνδέθηκε με την εργασία.');returnToAirbnb()}else alert('Η τεχνική προσφορά αποθηκεύτηκε.')}catch(e){alert('Η αποθήκευση απέτυχε. Δημιούργησε αντίγραφο ασφαλείας πριν κλείσεις.')}};
function preview(){if(!valid())return;const q=clientData();el('technical').classList.add('hidden');el('offerTypeBar').classList.add('hidden');el('techClient').classList.remove('hidden');el('techClient').innerHTML=`<div class="card tech-paper" style="max-width:850px;margin:auto"><div style="border-bottom:4px solid #0f4ccf;padding-bottom:18px"><b style="color:#0f4ccf;font-size:25px">MGV MyGreekVacations</b><h2>ΤΕΧΝΙΚΗ & ΟΙΚΟΝΟΜΙΚΗ ΠΡΟΣΦΟΡΑ</h2><h3>${esc(q.title)}</h3></div><div class="row" style="margin:20px 0">${[['Πελάτης',q.client],['ΑΦΜ',q.clientVat],['Χώρος',q.apartment],['Διεύθυνση',q.address],['Προσφορά αρ.',q.quoteNo],['Ημερομηνία',q.date]].map(([k,v])=>`<div><b>${k}:</b> ${esc(v||'—')}</div>`).join('')}</div>${section('Αντικείμενο εργασιών',q.scope)}${q.lines.map((r,i)=>`<div class="tech-stage" style="border-bottom:1px solid #dbe5f5;padding:14px 0"><b>${i+1}. ${esc(r.name)}</b><p style="white-space:pre-wrap">${esc(r.note)}</p><div style="text-align:right">${r.pricingMode==='flat'?`<b>${eur(r.labor)}</b>`:`${r.qty} ${esc(r.unit)} × ${eur(r.base)} = <b>${eur(r.labor)}</b>`}</div></div>`).join('')}<div class="summary" style="margin:20px 0">${[['Καθαρή αξία',q.net],['ΦΠΑ '+draft.vat+'%',q.vat],['Συνολική αξία',q.total]].map(([k,v])=>`<div class="sumrow"><b>${k}</b><b>${eur(v)}</b></div>`).join('')}</div>${section('Τεχνικές παρατηρήσεις',q.notes)}${section('Εξαιρέσεις',q.exclusions)}${section('Διάρκεια εργασιών',q.delivery)}${section('Ισχύς προσφοράς',q.validity)}${section('Τρόπος πληρωμής',q.payment)}<div class="actions tech-actions"><button class="primary" id="techPrintNow">Εκτύπωση / Αποθήκευση PDF</button><button class="ghost" id="techBack">Επιστροφή στην εσωτερική ανάλυση</button></div></div>`;el('techBack').onclick=()=>mode(true);el('techPrintNow').onclick=()=>window.print()}
function section(title,value){return value?`<div style="margin:18px 0"><b>${title}</b><p style="white-space:pre-wrap">${esc(value)}</p></div>`:''}
el('techPreview').onclick=preview;
el('techBackup').onclick=()=>{sync();const blob=new Blob([JSON.stringify({version:1,offers:quotes.filter(q=>q.type==='technical'),currentDraft:draft},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MGV_Technical_Offers_Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
el('techTemplate').onclick=()=>{if(draft.stages.length&&!confirm('Αντικατάσταση των σταδίων με το υπόδειγμα;'))return;sync();draft.title='Αντιμετώπιση ανερχόμενης υγρασίας υπογείου';draft.scope='Προεργασία, δημιουργία χημικού φράγματος με DUROSTICK HYDROSTOP WALL, στεγανοποίηση με DUROSTICK D-1 και αποκατάσταση τοιχοποιίας.';draft.notes='Η εφαρμογή, οι στρώσεις και οι χρόνοι αναμονής ακολουθούν τα ισχύοντα τεχνικά φυλλάδια του κατασκευαστή και τις συνθήκες του υποστρώματος. Η βαφή πραγματοποιείται αφού η επιφάνεια είναι κατάλληλη. Απαιτείται επιμέτρηση και έλεγχος αιτίας υγρασίας πριν την οριστικοποίηση.';draft.exclusions='Επισκευές ενεργών διαρροών δικτύων και διαφορετικών εξωτερικών πηγών εισροής νερού κοστολογούνται χωριστά.';draft.duration='Κατόπιν επιμέτρησης, πλέον χρόνων αναμονής και ωρίμανσης.';draft.stages=[['Προστασία χώρου, καθαρισμός και αποκομιδή','Προστασία δαπέδων και λοιπών επιφανειών. Τελικός καθαρισμός και απομάκρυνση προϊόντων καθαίρεσης.','κατ’ αποκοπή'],['Καθαίρεση και προετοιμασία','Αφαίρεση σαθρών και προσβεβλημένων επιχρισμάτων μέχρι σταθερό υπόστρωμα. Καθαρισμός σκόνης, αλάτων και υπολειμμάτων.','m²'],['Χημικό φράγμα — HYDROSTOP WALL','Διάνοιξη και καθαρισμός διατρημάτων, έγχυση υλικού και τελική σφράγιση σύμφωνα με τις οδηγίες εφαρμογής και το είδος και πάχος τοιχοποιίας.','τρέχ. μ.'],['Στεγανοποίηση — DUROSTICK D-1','Προετοιμασία υποστρώματος και εφαρμογή στεγανωτικού σε διαδοχικές στρώσεις. Επεξεργασία γωνιών και ενώσεων τοίχου–δαπέδου.','m²'],['Αποκατάσταση σοβάδων','Επισκευή φθορών και αποκατάσταση επιχρισμάτων με κατάλληλα συμβατά υλικά.','m²'],['Στοκάρισμα και εξομάλυνση','Στοκάρισμα, τρίψιμο και προετοιμασία των επισκευασμένων επιφανειών.','m²'],['Αστάρωμα και βαφή','Κατάλληλο αστάρι και δύο στρώσεις συμβατού χρώματος. Απόχρωση κατόπιν συνεννόησης.','m²']].map(([name,description,unit])=>({...stage(),name,description,unit}));render()};
draft=fresh();if(window.airbnbContext){draft.apartment=window.airbnbContext.apartment;draft.address=window.airbnbContext.address;draft.title=window.airbnbContext.work}render();
})();
